"""empty message

Revision ID: 1eff08ff4e41
Revises: 9d9fbc0de185
Create Date: 2023-05-18 21:29:18.140103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eff08ff4e41'
down_revision = '9d9fbc0de185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
